# Generated by Django 3.1.5 on 2021-01-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210114_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimage',
            name='image_url',
            field=models.URLField(max_length=2048),
        ),
    ]
