# Generated by Django 3.1.5 on 2021-01-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210114_0114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sales',
            new_name='product_sales',
        ),
        migrations.AddField(
            model_name='productsale',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
    ]
