# Generated by Django 3.1.5 on 2021-01-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210118_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_sales',
            field=models.ManyToManyField(related_name='product_sales', through='product.ProductSale', to='product.Sale'),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='is_sale',
            field=models.BooleanField(default=True),
        ),
    ]
