# Generated by Django 3.1.5 on 2021-01-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210119_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_sales',
        ),
        migrations.AddField(
            model_name='sale',
            name='product_sales',
            field=models.ManyToManyField(related_name='product_sales', through='product.ProductSale', to='product.Product'),
        ),
    ]
