# Generated by Django 3.1.5 on 2021-01-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210119_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product_sales',
        ),
        migrations.AddField(
            model_name='product',
            name='on_sale',
            field=models.ManyToManyField(through='product.ProductSale', to='product.Sale'),
        ),
    ]
