# Generated by Django 3.1.5 on 2021-01-20 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210120_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='on_sale',
        ),
        migrations.AddField(
            model_name='product',
            name='on_sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.sale'),
        ),
        migrations.DeleteModel(
            name='ProductSale',
        ),
    ]
