# Generated by Django 3.1.5 on 2021-01-20 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210120_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='on_sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='product.sale'),
        ),
    ]
