# Generated by Django 3.1.5 on 2021-01-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210114_1804'),
        ('product', '0012_product_stocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stocks',
        ),
        migrations.AddField(
            model_name='product',
            name='liked',
            field=models.ManyToManyField(null=True, through='product.Like', to='user.User'),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
