# Generated by Django 3.1.5 on 2021-01-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210114_0114'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked',
            field=models.ManyToManyField(null=True, through='product.Like', to='product.Product'),
        ),
    ]
